#Use JDK 21 as base image
FROM eclipse-temurin:21-jdk-alpine

#Install bash and maven (for running spring-boot:run)
RUN apk add --no-cache bash maven
#Set working directory
WORKDIR /app

#Copy pom.xml to cache dependencies
COPY pom.xml .

#Download dependencies (offline mode)
RUN mvn dependency:go-offline

#Copy source code
COPY src ./src
#Expose port
EXPOSE 8080

# Run Spring Boot with DevTools enabled
CMD ["mvn", "spring-boot:run"]